name: Build images
run-name: Build Docker images
on: [push]
jobs:
  build-and-publish-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
        - uses: actions/checkout@v2

        - name: Build and Publish head Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
              github-token: ${{ secrets.DOCKER_TOKEN }}
              image-name: caddy
              build-context: ./caddy
