name: Build images
run-name: Build Docker images
on: [push]
jobs:
  caddy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
        - uses: actions/checkout@v4

        - name: Build and Publish head Docker image
          uses: VaultVulp/gp-docker-action@1.6.0
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: caddy
              build-context: ./caddy
              custom-args: --platform=linux/arm64,linux/amd64
